intelligo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from pages.views import Home, BigO, Masters, Notes
from django.urls import path, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^notes/$', Notes.as_view(), name='notes'),
    url(r'^masters/$', Masters.as_view(), name='masters'),
    url(r'^bigO/$', BigO.as_view(), name='bigO'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/forms.py
from django import forms
from pages.models import ComplexityPost, MastersPost
from django.core.validators import validate_slug


class ComplexityForm(forms.ModelForm):
    post = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control col-12',
            'placeholder': 'Input Equation...'
        }
    ))
    guess = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control col-12 mt-2',
            'placeholder': 'Guess the lower bound'
        }
    ))

    # required for Model Forms
    class Meta:
        model = ComplexityPost
        fields = ('post', 'guess')


class MastersForm(forms.ModelForm):
    post_a = forms.IntegerField(required=True, widget=forms.NumberInput(
        attrs={
            'class': 'form-control col-sm-7 aria-label="Large" aria-describedby="inputGroup-sizing-lg"',
            'placeholder': 'Input a positive number...'
        }
    ))
    post_b = forms.IntegerField(required=True, widget=forms.NumberInput(
        attrs={
            'class': 'form-control col-sm-7 aria-label="Large" aria-describedby="inputGroup-sizing-lg"',
            'placeholder': 'Input a number greater than 1...'
        }
    ))
    post_k = forms.IntegerField(required=True, widget=forms.NumberInput(
        attrs={
            'class': 'form-control col-sm-7 aria-label="Large" aria-describedby="inputGroup-sizing-lg"',
            'placeholder': 'Input a positive number...'
        }
    ))
    post_i = forms.IntegerField(required=True, widget=forms.NumberInput(
        attrs={
            'class': 'form-control col-sm-7 aria-label="Large" aria-describedby="inputGroup-sizing-lg"',
            'placeholder': 'Input a positive number...'
        }
    ))

    class Meta:
        model = MastersPost
        fields = ('post_a', 'post_b', 'post_k', 'post_i')

pages/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css'%}" type="text/css">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/png">

    <!-- for loading LaTeX -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>
    <!-- for font awesome icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
    crossorigin="anonymous">

    <title>Intelligo</title>

</head>

<body>

    <header class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <div class="jumbotron">
            <div class="container">
                <h3 class="d-inline-block display-4">Intelligo</h3>
                <hr>
                <nav class="nav justify-content-center lead">
                    <a class="nav-link active" href="/#">Home</a>
                    <a class="nav-link" href="{% url 'notes' %}">Notes</a>
                    <a class="nav-link" href="{% url 'bigO' %}">Asymptotic Analysis</a>
                    <a class="nav-link" href="{% url 'masters' %}">Master's Method</a>
                </nav>
                <hr>
            </div>
    </header>

    <div class="container text-justify">
        {% block content %}
        replaced
        {% endblock %}
        <br>
    </div>

    <footer class="page-footer font-small blue pt-4 mt-5">
        <div class="container">
            <p class="text-muted text-center"> © 2019 Copyright | Tamara Alhajj | Honours Project</p>
        </div>
        <br>
    </footer>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

pages/templates/bigO.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-4 font-italic">Asymptotic Analysis Tool</h1>
        <p class="lead font-italic text-muted">Try it yourself! Enter an equation, then run the asymptotic analysis.</p>
        <p>
        This tool analyzes the input equation, <em>f(n)</em> in terms of <em>n</em>.
        So all other variables are not considered when deducing the final answer.
        <br>
        Also note input with python math expressions is REQUIRED.
        Please refer to the <a href="{% url 'notes' %}">usage information</a> section in the notes provided, for a summary of how to input in this way.
        <br>
        To guess g(n), such that g(n) is a upper bound to f(n), input the function as you do for f(n)
        </p>
    </div>
    <div class="row">
        <form class="form-group col-sm" method="post">
            <label for="id_post" style="font-size: 24px;">$$f(n) = $$</label>
            {% csrf_token %}
            {{ form.post }}
            {{ form.guess }}
            <button type="submit" class="btn btn-outline-primary container-fluid btn-lg mt-4">Run Analysis</button>
        </form>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="card-header">{{ title }}</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item" style="font-size: 24px;">Solution $${{ answer }}$$</li>
                <li class="list-group-item" style="font-size: 24px;">
                    {% for line in lim %}
                    {{ line }}
                    <br>
                    {% endfor %}
                </li>
                <li class="list-group-item" style="font-size: 24px;">
                    {% for line in more %}
                    {{ line }}
                    <br>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="carouselGraphIndicators" class="carousel slide container mt-4 text-center" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselGraphIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselGraphIndicators" data-slide-to="1"></li>
        <li data-target="#carouselGraphIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner text-center">
        <h1 class="display-5 p-3 mb-2 bg-warning text-white font-italic">Examples of the asymptotic notations</h1>
        <p class="lead text-muted">Number of operations versus input size for example functions</p>
        <div class="carousel-item active">
            <img class="d-block w-60 h-60 rounded img-fluid" src="{% static 'images/slowest.png'%}" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-60 h-60 rounded img-fluid" src="{% static 'images/fastest.png'%}" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-60 h-60 rounded img-fluid" src="{% static 'images/all.png'%}" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselGraphIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselGraphIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

{% endblock %}

pages/templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1 class="display-4 font-italic">Understanding Complexity</h1>
    <h5 class="text-muted">A web application to aid in understanding of asymptotic complexity theory.</h5>
    <p>
        The navbar will redirect you to the tools to provide asymptotic analysis of a given equation.
        Just follow the instructions given on the page, and be sure that all input is in python's math format.
        I hope this proves to be a helpful learning aid!
    </p>
    <!-- Take my survey and let me know what you think! -->
    <!-- <a class="btn btn-primary" href="https://forms.gle/D8GoWAofKnFEnPRn6" target="_blank">Take Survey</a> -->
</div>
<hr>
<br>
<div class="container">
    <h1 class="display-4 font-italic">About this project</h1>
    <p class="lead text-muted">Check it out on <a href="https://www.github.com/TamaraAlhajj/Intelligo" target="_blank">github <i class="fab fa-github"></i></a></p>
    <p>
    Intelligo is my undergraduate honours project, completed winter 2019.
    This project was intended to help those in COMP 3804 at Carleton University, in learning the basics of complexity theory.
    <br>
    Developed in chrome.
    <br>
    The web framework behind this application is <a href="https://www.djangoproject.com/" target="_blank">Django</a>.
    <br>
    The logic layer of this application was written in python3.7
    <br>
    The libraries I used with this are <a href="https://sympy.org/" target="_blank">SymPy</a>, <a href="https://pypi.org/project/anytree/" target="_blank">Anytree</a>, and <a href="https://graphviz.org/" target="_blank">graphviz</a>.
    </p>
</div>
<br>
{% endblock %}

pages/templates/masters.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="container text-center">
    <h1 class="display-4 font-italic">Master's Method Tool</h1>
    <p class="font-weight-light">
        This a tool to provide asymptotic analysis for divide-and-conquer recurrences, with the use of <a
            href="{% url 'bigO' %}">big-O notaion</a>.
        Just follow the rules stated above and enter your desired values for a, b, k, & i.
        The solution will be generated along with the recursion tree.
    </p>
    <div class="row">
        <form class="form-group col-12" method="post">
            <label for="id_post" class="lead">
                Input for Equation of the form, $$ T(n)=aT(\frac{n}{b})+ \Theta(n^{k}(log^{i}n))$$
            </label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg">a</span>
                </div>
                {% csrf_token %}
                {{ form.post_a }}
            </div>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg">b</span>
                </div>
                {% csrf_token %}
                {{ form.post_b }}
            </div>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg">k</span>
                </div>
                {% csrf_token %}
                {{ form.post_k }}
            </div>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg">i&nbsp;</span>
                </div>
                {% csrf_token %}
                {{ form.post_i }}
            </div>
            <button type="submit" class="btn btn-outline-primary container-fluid btn-lg mt-4">Run Analysis</button>
        </form>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-subtitle mb-2 text-muted">$${{ T }}$$</h5>
            <div class="container">
                {% for line in ans %}
                $${{ line }}$$
                <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="container mt-4">
    <div class="card">
        <div class="card-header text-muted">
            Recursion Tree
        </div>
        <div class="thumbnail">
            <div class="card-body caption">
                <div id="list">
                    <div class="responsive-iframe-container">
                        <pre>{{ tree_data|safe }}</pre>
                    </div>
                </div>

                <p>$${{ tree_msg }}$$</p>
                <p>$${{ height }}$$</p>
            </div>
            </a>
        </div>
    </div>
</div>


{% endblock %}

pages/templates/notes.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="container">
    <h1 class="display-4 font-italic">Simplifying Complexity</h1>
    <p>
        The asymptotic analysis of a given function is a means of finding the bounds of said function.
        As computer scientists, we are concerned with the complexity of a function because computers solve computational
        problems. By finding the complexities of our algorithms, we find the runtime of our programs.
        <em>But what does this mean?</em>$$O(n), \Omega(log(n)), \Omega(nlog(n)), \Theta(n^2)$$
        If your tasked to find the <em>worst-case runtime</em> of an algorithm, what would you do?
        What about the <em>best-case</em>?
    </p>
    <p>
        Not to worry!
        Once the terminology is clear, so are the steps.
        First things first, let us go over the input methods for the asymptotic complexity tool.
    </p>
    <div class="container mt-5">
        <h1 class="display-5 p-3 mb-2 bg-warning text-white">Usage Information</h1>
        <p> The following is a summay of how to input python math expressions, which is required to use the asymptotic complexity tool.</p>
        <ul class="list-group">
            <li class="list-group-item list-group-item-warning"><strong class="lead">Powers:</strong>$$n^i \longrightarrow n**i$$</li>
            <li class="list-group-item list-group-item-warning"><strong class="lead">Multiplication:</strong>$$nc \longrightarrow n*i$$</li>
            <li class="list-group-item list-group-item-warning"><strong class="lead">Division:</strong>$$\frac{n}{c} \longrightarrow n/c$$</li>
            <li class="list-group-item list-group-item-warning"><strong class="lead">Logarithms:</strong>$$logn \longrightarrow log(n)$$</li>
            <li class="list-group-item list-group-item-warning"><strong class="lead">Addition & Subtraction:</strong>$$n + a - b \longrightarrow n + a - b$$</li>
        </ul>
    </div>
    <br>
    <br>
    <p>Now that that's out of the way, let's move on to the interesting stuff.</p>
    <h1 class="display-5">Using Limits to Bound a Function</h1>
    <p>
        This method is quite simple. Given the function you are analyzing, f(n) we divide by some other function, g(n).
        All we must find is the limit of this quotient as n approaches infinity. The beauty is we can choose any
        function g(n), no pressure.
        Preferably, we would choose g(n) to be as tight a bound as possible... but you can also pick right out of a hat.
        Have a little fun with it.

        $$\text{Given functions: } f(n) \text{ and } g(n)$$

        $$\lim_{n \rightarrow \infty} \frac{f(n)}{g(n)} \rightarrow \textbf{ some answer we care about }$$

        Why do we care about this answer? Espesically, if g(n) can be <em>anything</em>.
        Well, based on the answer we find we can say something about the relationship between these two functions.
    </p>
    <p>
        If the limit as n grows to infinity is 0, we know from our solid maths skills the numerator grows slower than
        the denominator.<br>
        Which implies we have found an upper bound to f(n). <br>
        Similarly, if the limit as n grows to infinity is infinity. Then we know the numerator grows faster than the
        denominator.<br>
        Which implies we have found a lower bound to f(n).
    </p>

    <p>
        The following table shows details on all the notational terms common in the field asymptotic complexity.
    </p>

<hr>

    <table class="table text-center table-striped">
        <h3>Summary of Asymptotic Notation</h3>
        <thead class="thead-dark">
            <th scope="col">Notation</th>
            <th scope="col">Name</th>
            <th scope="col">Bound</th>
            <th scope="col">Limit</th>
        </thead>
        <tbody>
            <tr>
                <th scope="row">$$f(n) \in o(g(n))$$</th>
                <td>Little Oh</td>
                <td>$$f < g \therefore \text{ g(n) is an upper bound}$$</td> <td>$$\lim_{n \rightarrow \infty}
                        \frac{f(n)}{g(n)} = 0$$</td>
            </tr>
            <tr>
                <th scope="row">$$f(n) \in O(g(n))$$</th>
                <td>Big Oh</td>
                <td>$$f \leq g \therefore \text{ g(n) is an upper bound}$$</td>
                <td>$$\lim_{n \rightarrow \infty} \frac{f(n)}{g(n)} \in [0, \infty)$$</td>
            </tr>
            </tr>
            <tr>
                <th scope="row">$$f(n) \in \omega(g(n))$$</th>
                <td>Little Omega</td>
                <td>$$f > g \therefore \text{ g(n) is an lower bound}$$</td>
                <td>$$\lim_{n \rightarrow \infty} \frac{f(n)}{g(n)} = \infty$$</td>
            </tr>
            <tr>
                <th scope="row">$$f(n) \in \Omega(g(n))$$</th>
                <td>Big Omega</td>
                <td>$$f \geq g \therefore \text{ g(n) is an upper bound}$$</td>
                <td>$$\lim_{n \rightarrow \infty} \frac{f(n)}{g(n)} \in (0, \infty]$$</td>
            </tr>
            <tr>
                <th scope="row">$$f(n) \in \Theta(g(n))$$</th>
                <td>Theta</td>
                <td>$$f = g \therefore \text{ g(n) is an tight bound}$$</td>
                <td>$$\lim_{n \rightarrow \infty} \frac{f(n)}{g(n)} \in (0, \infty)$$</td>
            </tr>
        </tbody>
        <tfoot>
            <em class="text-muted">
                Note: Round brackets indicate inclusive range,
                whereas square brackets indicate exclusive range.
            </em>
        </tfoot>
    </table>

    <div class="container mt-4 text-center">
        <h1 class="display-5 p-3 mb-2 bg-warning text-white">Generalized Graphs of Asymptotic Notations</h1>
        <p class="lead text-muted">Number of operations versus input size for example functions</p>
        <img class="d-block w-60 h-60 rounded img-fluid" src="{% static 'images/asymptoticNotationGraphs.png'%}" alt="asymptotic example graphs">
    </div>

    <div class="row col-12 lead p-3 mt-2 mb-2">
        <div class="container col-3"><p>Big Theta is shown as a tight bound.</p></div>
        <div class="container col-3"><p>Big Oh is shown as a upper bound.</p></div>
        <div class="container col-3"><p>Big Omega is shown as a lower bound.</p></div>
    </div>

    <div class="container mt-4 text-center">
        <p><b>Disclaimer:</b> These graphs are not based on user input. They are examples to aid in visualizing the meaning of Big Oh, Theta, and Omega. </p>
        <p class="text-center text-muted mt-3"><i class="fa fa-book"></i> Cormen, T.H., et al. Introduction to Algorithms. MIT Press, 2009. Page 45.</p>
    </div>
</div>
<br>
<hr>
<div class="container mt-4">
    <h1 class="display-4 font-italic">Mastering Master's</h1>
    <p>
        The Master's Method, also known as the Master's Theorem, is a simple way to solve recurrences of the following
        form,
        $$ T(n)=aT(\frac{n}{b})+ \Theta(f(n))$$

        More specifically,

        $$T(n)=aT(\frac{n}{b})+ \Theta(n^{k}(log^{i}n))$$

        $$a \rightarrow \text{number of subproblems in recurrence relation}$$
        $$b \rightarrow \text{branching factor which reduces the subproblem with each recursive call}$$
        $$\text{Base Case} \rightarrow T(0) = \Theta(1)$$
    </p>
    <p>
        Moreover, the following variable must be defined using variables a and b,
        $$c_{critical} = \textit{the work to split/recombine vs subproblems}$$
        $$= \textit{log(# of subproblems)/log(relative problem size)}$$
        $$= log(a)/log(b)$$
        $$= log_{b} a $$
    </p>
    <p>This method can be used to solve all recurrences which adhere to the following rules:</p>
    <ul class="list-group">
        <li class="list-group-item list-group-item">a must be be at least 0</li>
        <li class="list-group-item list-group-item">b must be an integer larger than 1</li>
        <li class="list-group-item list-group-item">k must be at least 0</li>
        <li class="list-group-item list-group-item">i must be at least 0</li>
        <li class="list-group-item list-group-item">All argument values must be constants</li>
        <li class="list-group-item list-group-item">Must have polynomial difference between, $$f(n) \text{ and }
            n^{\log _{b} a}$$</li>
    </ul>
    <p class="mt-5">
        If each of these criteria is met, you may then solve your recurrence with the Master's Method! 
        So what is this method, you ask?
        The following table is a summary of what the theorem states,
        <table class="table text-center table-light">
            <thead class="thead-dark">
                <th scope="col">Case</th>
                <th scope="col">Condition</th>
                <th scope="col">Master's Theorem bound</th>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>$$f(n) = O(n^c) \textit{ such that } c < c_{critical}$$</td> 
                    <td>$$T(n) = \Theta(n^{c_{critical}})$$</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>$$f(n) = \Theta(n^{c_{critical}} log^{i} n)$$</td>
                    <td>$$T(n) = \Theta(n^{c_{critical}} log^{i+1} n)$$</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>$$ f(n) = \Omega(n^c) \textit{ such that } c > c_{critical}$$</td>
                    <td>$$T(n) = \Theta(f(n))$$</td>
                </tr>
            </tbody>
        </table>
    </p>
</div>
<br>
<hr>

{% endblock %}